post_install() {
	echo "	>> Create directory for log on /var/log/s6rc/rpcbind" 
	mkdir -p -m 0755 /var/log/s6rc/rpcbind
	chown -R s6log:log /var/log/s6rc/rpcbind
	
	echo "	>> Create directory for log on /var/log/s6rc/rpc.statd" 
	mkdir -p -m 0755 /var/log/s6rc/rpc.statd
	chown -R s6log:log /var/log/s6rc/rpc.statd
	
	echo "	>> Create directory for log on /var/log/s6rc/rpc.mountd" 
	mkdir -p -m 0755 /var/log/s6rc/rpc.mountd
	chown -R s6log:log /var/log/s6rc/rpc.mountd
}
